[package]
name = "starcoin-accumulator"
version = "1.10.0-rc.2"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"


[dependencies]
anyhow = "1.0.41"
once_cell = "1.8.0"
mirai-annotations = "1.10.1"
byteorder = "1.4.3"
itertools = { version = "0.10.3", default-features = false }
logger = {path = "../../commons/logger", package="starcoin-logger"}
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "b4887ba2f28171c0e1d825a03d6ab7fd456a7a02"}
bcs-ext = { package="bcs-ext", path = "../../commons/bcs_ext" }
serde = { version = "1.0.130" }
lru = "0.7.0"
parking_lot = "0.12.0"
schemars = {git = "https://github.com/starcoinorg/schemars", rev="88baec6c9c57e92718f1d84d2722677f9e2118cb"}

[dev-dependencies]
rand = "0.8.5"
rand_core = { version = "0.6.3", default-features = false }
proptest = "1.0.0"
proptest-derive = "0.3.0"

[features]
default = []
fuzzing = ["starcoin-crypto/fuzzing"]
