[package]
name = "starcoin-account-service"
version = "1.10.0-rc.2"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.41"
futures = "0.3.12"
async-trait = "0.1"
starcoin-logger = { path = "../../commons/logger" }
starcoin-types = { path = "../../types" }
bcs-ext = { package = "bcs-ext", path = "../../commons/bcs_ext" }
starcoin-config = { path = "../../config" }
starcoin-service-registry = { path = "../../commons/service-registry" }
starcoin-account-api = { path = "../api", features = ["mock"] }
starcoin-account = { path = "../" }
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "b4887ba2f28171c0e1d825a03d6ab7fd456a7a02"}
starcoin-chain-notify = { path = "../../chain/chain-notify" }


[dev-dependencies]
stest = { path = "../../commons/stest" }
tempfile = "3"

