[package]
name = "starcoin-transaction-builder"
version = "1.10.0-rc.2"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.41"
starcoin-config = { path = "../../config"}
stdlib = { package="stdlib", path = "../stdlib"}
starcoin-vm-types = { path = "../types"}
bcs-ext = { package="bcs-ext", path = "../../commons/bcs_ext" }
starcoin-logger = { path = "../../commons/logger"}
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "e2ed4bfd60eeca3d95da869ff978ab4596048761"}

[dev-dependencies]
stest = {path = "../../commons/stest"}
