[package]
name = "starcoin-chain-notify"
version = "1.10.0-rc.2"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.41"
starcoin-types = {path = "../../types" }
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "e2ed4bfd60eeca3d95da869ff978ab4596048761"}
starcoin-logger = {path = "../../commons/logger"}
starcoin-storage = { path = "../../storage" }
starcoin-service-registry = { path = "../../commons/service-registry" }
