[workspace]

members = [
    "commons/scs",
    "commons/crypto",
    "types",
    "config",
    "storage/state-store",
    "bus",
    "network",
    "consensus",
    "txpool",
    "rpc/json-rpc",
    "executor",
    "chain",
    "node"
]