[workspace]

members = [
    "commons/stest",
    "commons/scs",
    "commons/crypto",
    "commons/logger",
    "commons/transaction-pool",
    "types",
    "core/traits",
    "core/accumulator",
    "core/state-tree",
    "core/forkable-jellyfish-merkle",
    "core/statedb",
    "core/genesis",
    "config",
    "bus",
    "storage",
    "network",
    "consensus",
    "txpool",
    "rpc/json-rpc",
    "executor",
    "chain",
    "node",
    "sync",
    "miner",
    "node",
    "network-libp2p",
    "network-libp2p/peerset",
    "vm/vm-runtime",
]