[package]
name = "starcoin-txpool"
version = "0.1.0"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
actix = "0.9"
actix-rt = "1.0"
log = "0.4"
transaction-pool = "2.0"
futures = "0.3"
futures-channel = "0.3"
rand = "0.6"
serde = "1.0"
serde_derive = "1.0"
types = { package = "starcoin-types", path = "../types"}
config = {path = "../config", package="starcoin-config"}
bus = {path = "../bus", package="starcoin-bus"}
common_crypto = {package = "starcoin-crypto", path = "../commons/crypto"}