[package]
name = "starcoin-move-compiler"
version = "0.1.0"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0"
once_cell = "1.4.0"
tempfile = "3.1.0"
regex = { version = "1.3.7", default-features = false, features = ["std", "perf"] }
move-lang = { package="move-lang", git = "https://github.com/starcoinorg/libra", rev="45cecc9abf89c6f660a4debe5d95aeeaeff9dead" }
starcoin-crypto = { path = "../../commons/crypto"}
starcoin-vm-types = { path = "../types"}
