[package]
name = "starcoin-compiler"
version = "0.1.0"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
types = { package="starcoin-types", path = "../../types"}
compiler = { package="compiler", git = "https://github.com/starcoinorg/libra", rev="7a35ed6edb7921ab096028aed91b8e5ff11cc74d" }
logger = {path = "../../commons/logger", package="starcoin-logger"}
stest = {path = "../../commons/stest"}

[dev-dependencies]

