[package]
name = "starcoin-compiler"
version = "0.1.0"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
types = { package="starcoin-types", path = "../../types"}
compiler = { package="compiler", git = "https://github.com/libra/libra", rev="3193ec4b7afff05e9476fd923f331f18fb7f3050" }
logger = {path = "../../commons/logger", package="starcoin-logger"}
stest = {path = "../../commons/stest"}

[dev-dependencies]
env_logger = "0.7.1"

