[package]
name = "move-prover"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
publish = false
edition = "2018"
license = "Apache-2.0"

[dependencies]
# libra dependencies
move-lang = { git = "https://github.com/starcoinorg/libra", rev="627e66029eb748c1e3e05d6c8fd6db11935f80b4" }
spec-lang = { git = "https://github.com/starcoinorg/libra", rev="627e66029eb748c1e3e05d6c8fd6db11935f80b4" }
docgen = { git = "https://github.com/starcoinorg/libra", rev="627e66029eb748c1e3e05d6c8fd6db11935f80b4" }
stackless-bytecode-generator = { git = "https://github.com/starcoinorg/libra", rev="627e66029eb748c1e3e05d6c8fd6db11935f80b4" }
vm = { git = "https://github.com/starcoinorg/libra", rev="627e66029eb748c1e3e05d6c8fd6db11935f80b4" }
libra-types = { git = "https://github.com/starcoinorg/libra", rev="627e66029eb748c1e3e05d6c8fd6db11935f80b4" }
libra-temppath = { git = "https://github.com/starcoinorg/libra", rev="627e66029eb748c1e3e05d6c8fd6db11935f80b4" }
libra-workspace-hack = { git = "https://github.com/starcoinorg/libra", rev="627e66029eb748c1e3e05d6c8fd6db11935f80b4" }
bytecode-source-map = { git = "https://github.com/starcoinorg/libra", rev="627e66029eb748c1e3e05d6c8fd6db11935f80b4" }
move-ir-types = { git = "https://github.com/starcoinorg/libra", rev="627e66029eb748c1e3e05d6c8fd6db11935f80b4" }

# external dependencies
anyhow = "1.0.31"
clap = "2.33.1"
codespan = "0.8.0"
codespan-reporting = "0.8.0"
handlebars = "3.1.0"
itertools = "0.9.0"
log = "0.4.8"
num = "0.2.1"
pretty = "0.10.0"
regex = "1.3.9"
serde = { version = "1.0.111", features = ["derive"] }
simplelog = "0.8.0"
once_cell = "1.4.0"
toml = "0.5.6"

[dev-dependencies]
datatest-stable = {git = "https://github.com/starcoinorg/libra", rev="627e66029eb748c1e3e05d6c8fd6db11935f80b4" }
test-utils = {git = "https://github.com/starcoinorg/libra", rev="627e66029eb748c1e3e05d6c8fd6db11935f80b4" }

[[test]]
name = "testsuite"
harness = false
