[package]
name = "transaction-builder-generator"
version = "1.10.0-beta"
authors = ["Diem Association <opensource@diem.org>"]
description = "Diem transaction-builder"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.41"
heck = "0.3.3"
regex = "1.4.3"
structopt = "0.3.26"
textwrap = "0.14.0"
serde_yaml = "0.8.21"
serde-generate = {git="https://github.com/starcoinorg/serde-reflection" , rev="694048797338ff7385006d968e786b6d9dbdeb8b"}
serde-reflection = {git="https://github.com/starcoinorg/serde-reflection" , rev="694048797338ff7385006d968e786b6d9dbdeb8b"}

starcoin-vm-types = { path = "../types"}
move-core-types = {git = "https://github.com/starcoinorg/diem", rev="50125f4d1c16500a908c50cfd4236c3df77bd2a4"  }
bcs = "0.1.3"

[dev-dependencies]
tempfile = "3.2.0"
which = "4.1.0"

[features]
default = []

[[bin]]
name = "generate-transaction-builders"
path = "src/generate.rs"
test = false
