[package]
name = "starcoin-txpool-mock-service"
version = "1.10.0-rc.2"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.41"
async-trait = "0.1"
types = {path = "../../types", package="starcoin-types"}
crypto = { package = "starcoin-crypto", git = "https://github.com/starcoinorg/starcoin-crypto", rev = "e2ed4bfd60eeca3d95da869ff978ab4596048761"}
starcoin-txpool-api = {package = "starcoin-txpool-api", path ="../api"}
stest = {path = "../../commons/stest"}
futures-channel = "0.3"

[dev-dependencies]
