[package]
name = "network-api"
version = "1.10.0-beta"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"

[dependencies]
hex= "0.4.3"
anyhow = "1.0.41"
futures = "0.3.12"
serde = { version = "1.0.130", default-features = false }
rand = "0.8.4"
itertools = "0.10.3"
async-trait = "0.1.51"
parking_lot = "0.12.0"

starcoin-logger = { path = "../../commons/logger"}
starcoin-types = { path = "../../types" }
starcoin-crypto = { path = "../../commons/crypto" }
bcs-ext = { package = "bcs-ext", path = "../../commons/bcs_ext" }
starcoin-service-registry = { path = "../../commons/service-registry" }
network-p2p-types = {path = "../../network-p2p/types"}
schemars = {git = "https://github.com/starcoinorg/schemars", rev="0f4982ec30d6117fcf5734963b0dc8c87bc5dff7"}
starcoin-metrics = {path = "../../commons/metrics"}
