[package]
name = "network-api"
version = "1.10.0-rc.2"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"

[dependencies]
hex= "0.4.3"
anyhow = "1.0.41"
futures = "0.3.12"
serde = { version = "1.0.130", default-features = false }
rand = "0.8.5"
itertools = "0.10.3"
async-trait = "0.1.51"
parking_lot = "0.12.0"

starcoin-logger = { path = "../../commons/logger"}
starcoin-types = { path = "../../types" }
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "e2ed4bfd60eeca3d95da869ff978ab4596048761"}
bcs-ext = { package = "bcs-ext", path = "../../commons/bcs_ext" }
starcoin-service-registry = { path = "../../commons/service-registry" }
network-p2p-types = {path = "../../network-p2p/types"}
schemars = {git = "https://github.com/starcoinorg/schemars", rev="960ebefac4dd54e6f9302db9f9429141ce3ea67a"}
starcoin-metrics = {path = "../../commons/metrics"}
