[package]
name = "starcoin-config-generator"
version = "0.1.0"
authors = ["nonsense <nonsense0202@pm.me>"]
edition = "2018"

[dependencies]
starcoin-config = {path="../../config"}
structopt = "0.3.2"
