[package]
name = "starcoin-network-rpc-api"
version = "1.10.0-rc.2"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
once_cell = "1.8.0"

starcoin-types = { path = "../../types" }
network-rpc-core = { path = "../core" }
starcoin-accumulator = { path = "../../commons/accumulator" }
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "e2ed4bfd60eeca3d95da869ff978ab4596048761"}
starcoin-state-api = { path = "../../state/api" }
starcoin-state-tree = { path = "../../state/state-tree" }
network-rpc-derive = { path = "../derive" }
bcs-ext = { path = "../../commons/bcs_ext", package = "bcs-ext" }
starcoin-logger = {path = "../../commons/logger"}
serde = { version = "1.0.130", features = ["derive"] }
anyhow = "1.0.41"
futures = "0.3.12"
