[package]
name = "vm-status-translator"
version = "1.10.0-beta"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "~1"
anyhow = "~1"
starcoin-vm-types = {path = "../types"}
starcoin-move-explain = {path = "../move-explain"}
schemars = {git = "https://github.com/starcoinorg/schemars", rev="067cce1fed5e6d12206616e785a213132912bbf7"}
