[package]
name = "starcoin-context"
version = "0.1.0"
authors = ["fanngyuan <fanngyuan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.9"
actix-rt = "1.0"
futures = "0.3.4"
