[package]
name = "starcoin-sync-api"
version = "1.10.0-rc.2"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"

[dependencies]
anyhow = "1.0.41"
starcoin-types = {path = "../../types", package="starcoin-types"}
starcoin-logger = {path = "../../commons/logger", package="starcoin-logger"}
async-trait = "0.1"
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "e2ed4bfd60eeca3d95da869ff978ab4596048761"}
serde = { version = "1.0.130", default-features = false }
starcoin-accumulator = {path = "../../commons/accumulator"}
starcoin-service-registry = { path = "../../commons/service-registry" }
stream-task ={ path = "../../commons/stream-task"}
network-api = {path = "../../network/api", package="network-api"}
schemars = {git = "https://github.com/starcoinorg/schemars", rev="960ebefac4dd54e6f9302db9f9429141ce3ea67a"}
