[package]
name = "starcoin-sync-api"
version = "1.10.0-rc.2"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"

[dependencies]
anyhow = "1.0.41"
starcoin-types = {path = "../../types", package="starcoin-types"}
starcoin-logger = {path = "../../commons/logger", package="starcoin-logger"}
async-trait = "0.1"
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "b4887ba2f28171c0e1d825a03d6ab7fd456a7a02"}
serde = { version = "1.0.130", default-features = false }
starcoin-accumulator = {path = "../../commons/accumulator"}
starcoin-service-registry = { path = "../../commons/service-registry" }
stream-task ={ path = "../../commons/stream-task"}
network-api = {path = "../../network/api", package="network-api"}
schemars = {git = "https://github.com/starcoinorg/schemars", rev="88baec6c9c57e92718f1d84d2722677f9e2118cb"}
