[package]
name = "starcoin-sync-api"
version = "1.10.0-beta"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"

[dependencies]
anyhow = "1.0.41"
starcoin-types = {path = "../../types", package="starcoin-types"}
starcoin-logger = {path = "../../commons/logger", package="starcoin-logger"}
async-trait = "0.1"
starcoin-crypto = { package="starcoin-crypto", path = "../../commons/crypto"}
serde = { version = "1.0.130", default-features = false }
starcoin-accumulator = {path = "../../commons/accumulator"}
starcoin-service-registry = { path = "../../commons/service-registry" }
stream-task ={ path = "../../commons/stream-task"}
network-api = {path = "../../network/api", package="network-api"}
schemars = {git = "https://github.com/starcoinorg/schemars", rev="a40307e45dd9a62026d1b231690d2b4472c9cabb"}
