[package]
name = "starcoin-vm-types"
version = "1.10.0-rc.2"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.41"
once_cell = "1.8.0"
rand = "0.8.5"
serde = { version = "1.0.130", default-features = false }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
serde_bytes = "0.11.5"
serde-helpers = {path = "../../commons/serde-helpers"}
num_enum = "0.5.6"
hex = "0.4.3"
chrono = { version = "0.4.19", default-features = false, features = ["clock"] }
mirai-annotations = "1.10.1"
log = "0.4.14"
bech32 = "0.8"

proptest = { version = "1.0.0", default-features = false, optional = true }
proptest-derive = { version = "0.3.0", default-features = false, optional = true }
move-core-types = { git = "https://github.com/starcoinorg/move", rev = "1d252312cdce83c10c93be349c21390a2b9a465a" }
move-vm-types = { git = "https://github.com/starcoinorg/move", rev = "1d252312cdce83c10c93be349c21390a2b9a465a" }
move-bytecode-verifier = { git = "https://github.com/starcoinorg/move", rev = "1d252312cdce83c10c93be349c21390a2b9a465a" }
vm = { package = "move-binary-format", git = "https://github.com/starcoinorg/move", rev = "1d252312cdce83c10c93be349c21390a2b9a465a"}
move-ir-types = { git = "https://github.com/starcoinorg/move", rev = "1d252312cdce83c10c93be349c21390a2b9a465a" }

bcs-ext = { package = "bcs-ext", path = "../../commons/bcs_ext" }
#starcoin-proptest-helpers = { path = "../../commons/proptest-helpers", optional = true }
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "b4887ba2f28171c0e1d825a03d6ab7fd456a7a02"}
starcoin-accumulator = { path = "../../commons/accumulator"}
forkable-jellyfish-merkle = { path = "../../commons/forkable-jellyfish-merkle"}
schemars = {git = "https://github.com/starcoinorg/schemars", rev="88baec6c9c57e92718f1d84d2722677f9e2118cb"}
[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
vm = { package = "move-binary-format", git = "https://github.com/starcoinorg/move", rev = "1d252312cdce83c10c93be349c21390a2b9a465a", features = ["fuzzing"]}
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "b4887ba2f28171c0e1d825a03d6ab7fd456a7a02"}
#starcoin-proptest-helpers = { path = "../../commons/proptest-helpers"}

[features]
default = []
fuzzing = ["proptest", "proptest-derive", "vm/fuzzing", "starcoin-crypto/fuzzing", "move-core-types/fuzzing"]
