[package]
name = "starcoin-vm-types"
version = "1.10.0-beta"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.41"
once_cell = "1.8.0"
rand = "0.8.4"
serde = { version = "1.0.130", default-features = false }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
serde_bytes = "0.11.5"
serde-helpers = {path = "../../commons/serde-helpers"}
num_enum = "0.5.6"
hex = "0.4.3"
chrono = { version = "0.4.19", default-features = false, features = ["clock"] }
mirai-annotations = "1.10.1"
log = "0.4.14"
bech32 = "0.8"

proptest = { version = "1.0.0", default-features = false, optional = true }
proptest-derive = { version = "0.3.0", default-features = false, optional = true }
move-core-types = { git = "https://github.com/starcoinorg/diem", rev = "4993b33a557d6cfad4df8c29a1ed961dfff918e7" }
move-vm-types = { git = "https://github.com/starcoinorg/diem", rev = "4993b33a557d6cfad4df8c29a1ed961dfff918e7" }
move-bytecode-verifier = { git = "https://github.com/starcoinorg/diem", rev = "4993b33a557d6cfad4df8c29a1ed961dfff918e7" }
vm = { git = "https://github.com/starcoinorg/diem", package = "move-binary-format", rev = "4993b33a557d6cfad4df8c29a1ed961dfff918e7"}
move-ir-types = { git = "https://github.com/starcoinorg/diem", rev = "4993b33a557d6cfad4df8c29a1ed961dfff918e7" }

bcs-ext = { package = "bcs-ext", path = "../../commons/bcs_ext" }
starcoin-proptest-helpers = { path = "../../commons/proptest-helpers", optional = true }
starcoin-crypto = { path = "../../commons/crypto" }
starcoin-accumulator = { path = "../../commons/accumulator"}
forkable-jellyfish-merkle = { path = "../../commons/forkable-jellyfish-merkle"}
schemars = {git = "https://github.com/starcoinorg/schemars", rev="a40307e45dd9a62026d1b231690d2b4472c9cabb"}
[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
vm = { git = "https://github.com/starcoinorg/diem",package = "move-binary-format", rev = "4993b33a557d6cfad4df8c29a1ed961dfff918e7", features = ["fuzzing"]}
starcoin-crypto = { path = "../../commons/crypto", features = ["fuzzing"] }
starcoin-proptest-helpers = { path = "../../commons/proptest-helpers"}

[features]
default = []
fuzzing = ["proptest", "proptest-derive", "starcoin-proptest-helpers", "vm/fuzzing", "starcoin-crypto/fuzzing", "move-core-types/fuzzing"]
