[package]
name = "starcoin-accumulator"
version = "0.1.0"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"


[dependencies]
anyhow = "1.0"
once_cell = "1.3.1"
mirai-annotations = "1.5.0"
byteorder = "1.3.2"
itertools = { version = "0.8.0", default-features = false }

types = {path = "../../types", package="starcoin-types"}
starcoin-crypto = { package="starcoin-crypto", path = "../../commons/crypto"}
scs = { package="starcoin-canonical-serialization", path = "../../commons/scs"}
serde = { version = "1.0" }
