[package]
name = "starcoin-uint"
version = "1.10.0-rc.2"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "e2ed4bfd60eeca3d95da869ff978ab4596048761"}
serde = { version = "1.0.130", default-features = false }
uint = "0.9.3"
hex = { version = "0.4.3", default-features = false }
[dev-dependencies]
bcs-ext = { path = "../../commons/bcs_ext" }
starcoin-types = { path = "../../types/"}
serde_json = "1.0"
