[package]
name = "starcoin-dev"
version = "1.10.0-rc.2"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.41"
thiserror = "1.0"
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "e2ed4bfd60eeca3d95da869ff978ab4596048761"}
starcoin-vm-types = { path = "../types" }
starcoin-vm-runtime = { path = "../vm-runtime"}
starcoin-logger = {path = "../../commons/logger"}
starcoin-state-api = { path = "../../state/api"}
starcoin-statedb = { path = "../../state/statedb"}
starcoin-resource-viewer = {path = "../resource-viewer"}
starcoin-abi-resolver = {path = "../../abi/resolver"}
starcoin-abi-decoder = {path = "../../abi/decoder"}
starcoin-abi-types = {path = "../../abi/types"}
bcs-ext = {path  = "../../commons/bcs_ext" }
