[package]
name = "starcoin-storage"
version = "0.1.0"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
serde = { version = "1.0" }
types = {path = "../types", package="starcoin-types"}
crypto = { package="starcoin-crypto", path = "../commons/crypto"}
scs = { package="starcoin-canonical-serialization", path = "../commons/scs"}

[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"
rev = "3cd18c44d160a3cdba586d6502d51b7cc67efc59"