[package]
name = "starcoin-storage"
version = "0.1.0"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
serde = { version = "1.0" }
types = {path = "../types", package="starcoin-types"}
crypto = { package="starcoin-crypto", path = "../commons/crypto"}
scs = { package="starcoin-canonical-serialization", path = "../commons/scs"}
chrono = "0.4"
byteorder = "1.3.2"
state-tree = { package="starcoin-state-tree", path = "../core/state-tree"}
starcoin-accumulator = { package="starcoin-accumulator", path = "../core/accumulator"}
forkable-jellyfish-merkle = { path = "../core/forkable-jellyfish-merkle", package = "forkable-jellyfish-merkle" }
logger = {path = "../commons/logger", package="starcoin-logger"}
libra-temppath = {path = "/Volumes/jiayi/project/rust/libra/common/temppath"}

[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"
rev = "72e45c3f3283302c825d53c3cd7154f4cd9e8f5b"