[package]
name = "starcoin-crypto"
version = "1.10.0-beta"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
serde = { version = "1.0.130" }
serde_bytes = "0.11.5"
hex = "0.4.3"
anyhow = "1.0"
diem-crypto = { package="diem-crypto",  git = "https://github.com/starcoinorg/diem", rev="4993b33a557d6cfad4df8c29a1ed961dfff918e7" , features = ["fuzzing"] }
diem-crypto-derive = { package="diem-crypto-derive",  git = "https://github.com/starcoinorg/diem", rev="4993b33a557d6cfad4df8c29a1ed961dfff918e7"  }
bcs-ext = { package="bcs-ext", path = "../bcs_ext" }
crypto-macro = { package="starcoin-crypto-macro", path = "./crypto-macro"}
rand = "0.8.4"
rand_core = { version = "0.6.3", default-features = false }
once_cell = "1.8.0"
serde-name = "0.2"

[features]
default = []
fuzzing = ["diem-crypto/fuzzing"]
#cargo build --release --features=avx512f
avx512f = ["diem-crypto/avx512f"]