[package]
name = "starcoin-abi-resolver"
version = "1.10.0-beta"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
starcoin-vm-types = {path = "../../vm/types"}
starcoin-abi-types = {path = "../types"}
anyhow="~1"
starcoin-resource-viewer = {path = "../../vm/resource-viewer"}
move-model = { git = "https://github.com/starcoinorg/diem", rev="4993b33a557d6cfad4df8c29a1ed961dfff918e7"  }
[dev-dependencies]
stdlib = {path = "../../vm/stdlib"}
serde_json = "1"
test-helper= {path = "../../test-helper"}
