[package]
name = "starcoin-executor"
version = "0.1.0"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"


[dependencies]
anyhow = "1.0"
once_cell = "1.2.0"
types = { package="starcoin-types", path = "../types"}
config = { package="starcoin-config", path = "../config"}
traits = {package="starcoin-traits", path = "../core/traits"}
crypto = { package="starcoin-crypto", path = "../commons/crypto"}
scs = { package="starcoin-canonical-serialization", path = "../commons/scs"}
state-tree = {path = "../core/state-tree", package="starcoin-state-tree"}
vm-runtime = { package="starcoin-vm-runtime", path = "../vm/vm-runtime"}
