[package]
name = "starcoin-faucet"
version = "0.1.0"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0"
starcoin-logger = { path = "../../commons/logger" }
starcoin-config = { path = "../../config"}
starcoin-wallet-api = {path = "../../wallet/api"}
starcoin-types = {path = "../../types"}
starcoin-rpc-client = { path = "../../rpc/client"}
[[bin]]
name = "faucet"
path = "src/main.rs"

[features]
default = []
