[package]
name = "starcoin-functional-tests"
version = "0.1.0"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0"
tempfile = "3.1.0"
datatest-stable = {git = "https://github.com/starcoinorg/libra", rev="a65fce0cd5bd321c2a6ecf8e2a29ff78afca67a9" }
vm = { package="vm", git = "https://github.com/starcoinorg/libra", rev="a65fce0cd5bd321c2a6ecf8e2a29ff78afca67a9" }
bytecode-verifier = { package="bytecode-verifier", git = "https://github.com/starcoinorg/libra", version = "0.1.0",rev="a65fce0cd5bd321c2a6ecf8e2a29ff78afca67a9" }
libra_types = { package="libra-types", git = "https://github.com/starcoinorg/libra", rev="a65fce0cd5bd321c2a6ecf8e2a29ff78afca67a9" }
move-lang = { package="move-lang", git = "https://github.com/starcoinorg/libra", rev="a65fce0cd5bd321c2a6ecf8e2a29ff78afca67a9" }
functional-tests = { package="functional-tests", git = "https://github.com/starcoinorg/libra", rev="a65fce0cd5bd321c2a6ecf8e2a29ff78afca67a9" }
stdlib = { package="stdlib", path = "../stdlib"}
starcoin_language_e2e_tests = { package="language-e2e-tests", path = "../e2e-tests"}
once_cell = "1.3.1"
regex = { version = "1.3.6", default-features = false, features = ["std", "perf"] }
thiserror = "1.0"
aho-corasick = "0.7.10"
termcolor = "1.0.5"
mirai-annotations = "1.6.0"
libra-crypto = { package="libra-crypto", git = "https://github.com/starcoinorg/libra", rev="a65fce0cd5bd321c2a6ecf8e2a29ff78afca67a9" }
libra-config = { package="libra-config", git = "https://github.com/starcoinorg/libra", rev="a65fce0cd5bd321c2a6ecf8e2a29ff78afca67a9" }
move-core-types = { package="move-core-types", git = "https://github.com/starcoinorg/libra", rev="a65fce0cd5bd321c2a6ecf8e2a29ff78afca67a9" }
libra-state-view = { package="libra-state-view", git = "https://github.com/starcoinorg/libra", rev="a65fce0cd5bd321c2a6ecf8e2a29ff78afca67a9" }
types = { package="starcoin-types", path = "../../types"}

[[test]]
name = "testsuite"
harness = false