[package]
name = "starcoin-sync"
version = "0.1.0"
authors = ["tiangong3624749 <tiangong3624749@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chain = {path = "../chain", package="starcoin-chain" }
anyhow = "1.0"
actix = "0.9"
config = {path = "../config", package="starcoin-config"}
network = {path = "../network", package="starcoin-network"}
types = {path = "../types", package = "starcoin-types" }
crypto = { package="starcoin-crypto", path = "../commons/crypto"}
itertools = { version = "0.8.0", default-features = false }
atomic_refcell = "0.1.3"

