[package]
name = "starcoin-consensus"
version = "0.1.0"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.9"
config = {path = "../config", package="starcoin-config"}
network = {path = "../network", package="starcoin-network"}
