[package]
name = "starcoin-json-rpc"
version = "0.1.0"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
hex = { version = "0.3.2", default-features = false }
serde = { version = "1.0", features = ["derive"] }
actix = "0.9"
actix-rt = "1.0"
jsonrpc-core = "14.0"
jsonrpc-derive = "14.0"
jsonrpc-http-server = "14.0"
jsonrpc-tcp-server = "14.0"
jsonrpc-ws-server = "14.0"
jsonrpc-server-utils = "14.0"
jsonrpc-pubsub = "14.0"
futures = { version = "0.3.2", features = ["compat"] }
num_cpus = "1.10"
scs = { package="starcoin-canonical-serialization", path = "../../commons/scs"}
types = { package="starcoin-types", path = "../../types"}
config = {path = "../../config", package="starcoin-config"}
txpool = {path = "../../txpool", package="starcoin-txpool"}
libra-crypto = { package="libra-crypto",  git = "https://github.com/libra/libra", rev="3193ec4b7afff05e9476fd923f331f18fb7f3050" }
libra-crypto-derive = { package="libra-crypto-derive",  git = "https://github.com/libra/libra", rev="3193ec4b7afff05e9476fd923f331f18fb7f3050" }
