[package]
name = "starcoin-move-explain"
version = "1.10.0-beta"
authors = ["Diem Association <opensource@diem.org>"]
description = "Diem Move abort code explanations"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
structopt = "0.3.26"
stdlib = { package="stdlib", path = "../stdlib"}
move-core-types = { git = "https://github.com/starcoinorg/diem", rev = "425c2049fb1e31a43f5943c28a94a23954fe0186" }
bcs-ext = { package="bcs-ext", path = "../../commons/bcs_ext" }

[features]
default = []
