[package]
name = "starcoin-natives"
version = "1.10.0-beta"
authors = ["caojiafeng <funfriendcjf@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
move-errmapgen = { git = "https://github.com/starcoinorg/diem", rev="425c2049fb1e31a43f5943c28a94a23954fe0186" }
move-docgen = { git = "https://github.com/starcoinorg/diem", rev="425c2049fb1e31a43f5943c28a94a23954fe0186" }
move-command-line-common = { git = "https://github.com/starcoinorg/diem", rev="425c2049fb1e31a43f5943c28a94a23954fe0186" }
move-prover = { git = "https://github.com/starcoinorg/diem", rev="425c2049fb1e31a43f5943c28a94a23954fe0186" }
move-stdlib = { git = "https://github.com/starcoinorg/diem", rev="425c2049fb1e31a43f5943c28a94a23954fe0186" }
move-vm-types = { git = "https://github.com/starcoinorg/diem", rev="425c2049fb1e31a43f5943c28a94a23954fe0186" }
move-vm-runtime = { git = "https://github.com/starcoinorg/diem", rev="425c2049fb1e31a43f5943c28a94a23954fe0186" }
move-binary-format = { git = "https://github.com/starcoinorg/diem", rev="425c2049fb1e31a43f5943c28a94a23954fe0186" }
move-core-types = { git = "https://github.com/starcoinorg/diem", rev="425c2049fb1e31a43f5943c28a94a23954fe0186" }
starcoin-crypto={path = "../../commons/crypto"}
log = "0.4.14"
walkdir = "2.3.1"
smallvec = "1.8.0"
tiny-keccak={version="2", features = ["keccak"]}
libsecp256k1 = "0.7.0"
arrayref = "0.3"
ripemd160 = "0.9.1"
num_enum = "0.5.6"
starcoin-uint = {path = "../../types/uint"}
starcoin-vm-types=  {path = "../types"}

[dev-dependencies]
rand = "0.8.4"
hex = "0.4"

[features]
testing=["move-stdlib/testing"]
