[package]
name = "starcoin-chain"
version = "0.1.0"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
actix = "0.9"
types = {path = "../types", package="starcoin-types"}
config = {path = "../config", package="starcoin-config"}
chain-state = {path = "../core/chain-state", package="starcoin-chain-state"}
state-tree = {path = "../core/state-tree", package="starcoin-state-tree"}
executor = {path = "../executor", package="starcoin-executor"}
crypto = { package="starcoin-crypto", path = "../commons/crypto"}
consensus = { package="starcoin-consensus", path = "../consensus"}
scs = { package="starcoin-canonical-serialization", path = "../commons/scs"}