[package]
name = "starcoin-chain-api"
version = "0.1.0"
authors = ["tiangong3624749 <tiangong3624749@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
types = {path = "../../types", package="starcoin-types"}
anyhow = "1.0"
async-trait = "0.1"
