[package]
name = "starcoin-proptest-helpers"
version = "0.4.1"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
crossbeam = "0.7.3"
diem-proptest-helpers = { package="diem-proptest-helpers",  git = "https://github.com/starcoinorg/diem", rev="e630621e3e41bf18236a3a17da5442c3eeb7ace1" }

proptest = "1.0.0"
proptest-derive = "0.3.0"
