on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Build release
    strategy:
      matrix:
        platform:
          - ubuntu-16.04
        toolchain:
          - stable
    runs-on: ${{matrix.platform}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: setup environment
        run: bash ./scripts/dev_setup.sh
      - name: build for linux
        uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: -Clink-arg=-Wl,--no-keep-memory,-fuse-ld=gold,--no-map-whole-files
        with:
          command: build
          args: --release --all --feature final
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: upload artifact
          uses: actions/upload-artifact@v1
          with:
            name: ${{matrix.platform}}.artifacts.zip
            path: target/release/
