[package]
name = "stream-task"
version = "1.10.0-beta"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"

[dependencies]
anyhow = "1.0.41"
thiserror = "1.0"
pin-utils = "0.1.0"
async-std = "1.10"
futures = "0.3.12"
futures-timer = "3.0"
futures-retry = "0.5.0"
pin-project = "0.4.8"
log = "0.4.14"
serde = { version = "1.0.130", features = ["derive"] }
parking_lot = "0.12.0"
schemars = {git = "https://github.com/starcoinorg/schemars", rev="d89e25ac045f485e5f4bfcb5527720df5ebbc037"}

[dev-dependencies]
stest = { path = "../stest" }
starcoin-logger = { path = "../logger"}
