[package]
name = "starcoin-account-api"
version = "1.10.0-rc.2"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.41"
thiserror = "1.0"
async-trait = "0.1"
serde = { version = "1.0.130", default-features = false }
serde_bytes = "0.11.5"
serde_json = "~1"
bcs-ext ={package= "bcs-ext", path = "../../commons/bcs_ext" }
hex= "0.4.3"
starcoin-types = { path = "../../types"}
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "b4887ba2f28171c0e1d825a03d6ab7fd456a7a02"}
rand = "0.8.5"
rand_core = { version = "0.6.3", default-features = false }
futures = "0.3.12"
starcoin-service-registry = { path = "../../commons/service-registry" }
schemars = {git = "https://github.com/starcoinorg/schemars", rev="88baec6c9c57e92718f1d84d2722677f9e2118cb"}

[dev-dependencies]

[features]
mock = []
